storage: ./storage
listen: 0.0.0.0:8000
web:
  title: npm.invo.zone
  logo: ./imgs/logo.png
  primary_color: "#2176ff"
  favicon: ./imgs/favicon.png
  login: true
  showSettings: true
  showInfo: false
  showSearch: true
  showFooter: false
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
logs: 
  { type: file, path: npm.invo.log, level: debug, format: pretty-timestamped, colors: true }
